### ISSUE TITLE
Package installation broken for Laravel 5

### ISSUE THREAD

**Issue by AlbertoRico** [liebig/cron#55] opened 2015-02-17 10:55 UTC
In step 4 of the [installation process](https://github.com/liebig/cron#installation), I get an error (below) when trying to run the Artisan migration:

Digging around, I've found a [discussion on the Laracasts forums](https://laracasts.com/discuss/channels/general-discussion/l5-latest-commit-breaks-if-using-waygenerators-or-image-internvention/) where it's pointed out this could be related to the new structure of Laravel 5.

Anybody has any idea about this?

    exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php:226
    Stack trace:
    #0 /home/vagrant/myApplication/vendor/liebig/cron/src/Liebig/Cron/CronServiceProvider.php(22): Illuminate\Support\ServiceProvider->__call('package', Array)
    #1 /home/vagrant/myApplication/vendor/liebig/cron/src/Liebig/Cron/CronServiceProvider.php(22): Liebig\Cron\CronServiceProvider->package('liebig/cron')
    #2 [internal function]: Liebig\Cron\CronServiceProvider->boot()
    #3 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Container/Container.php(523): call_user_func_array(Array, Array)
    #4 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(631): Illuminate\Container\Container->call(Array)
    #5 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(613): Illuminate\Foundation\Application->bootProvider(Object(Liebig\Cron\CronServiceProvider))
    #6 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Liebig\Cron\CronServiceProvider), 19)
    #7 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(614): array_walk(Array, Object(Closure))
    #8 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(15): Illuminate\Foundation\Application->boot()
    #9 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(165): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
    #10 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(192): Illuminate\Foundation\Application->bootstrapWith(Array)
    #11 /home/vagrant/myApplication/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\Foundation\Console\Kernel->bootstrap()
    #12 /home/vagrant/myApplication/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #13 {main}

**Comment by liebig** [comment] 2015-02-19 06:49
Thank you for using Cron. It seems that the ServiceProvider architecture changed in Laravel 5. I will check this next week.

**Comment by robert83ft** [comment] 2015-02-23 09:59
I tried to update my app from Laravel4 to Laravel5 and had the same issue as AlbertoRico. Can you help?

Robert

**Comment by liebig** [comment] 2015-02-23 12:05
I am working on this. I will give you an update in a few hours. By the way, I think this is not a bug but a feature request because Laravel 5 breaks nearly every package...

**Comment by robert83ft** [comment] 2015-02-23 12:06
I agree. Thanks for your support. Robert

**Comment by liebig** [comment] 2015-02-23 14:57
Okay, this is much work. I cannot get Cron running in one day. Laravel 5 changed so much. I will work on this and give you feedback in the next days.

**Comment by dcelasun** [comment] 2015-02-24 12:34
@liebig You can probably use [this](https://github.com/morrislaptop/LaravelFivePackageBridges) for an easier migration to L5.

**Comment by liebig** [comment] 2015-02-24 13:13
Thank you, @dcelasun. But I am working on a native L5 solution. The biggest problem at the moment is, that the Laravel 5 `Config` works different. I hope I can push a first update later this day.

**Comment by liebig** [comment] 2015-02-24 17:13
Work is done! Please test for Laravel 5:
1. Add "`liebig/cron": "dev-master"` to your /path/to/laravel/composer.json file at the `"require":` section
2. Run the `composer update liebig/cron --no-dev` command in your shell from your /path/to/laravel/ directory
3. Add `'Liebig\Cron\Laravel5ServiceProvider'` to your `'providers'` array in the /path/to/laravel/config/app.php file
4. Migrate the database with running the command `php artisan migrate --path=vendor/liebig/cron/src/migrations`
5. Publish the configuration file with running the command `php artisan vendor:publish` - now you find the Cron configuration file at /path/to/laravel/app/config/liebigCron.php and this file won't be overwritten at any update
6. Now you can use `Cron` everywhere for free

Please give me a short feedback. Thank you for your support :)

**Comment by robert83ft** [comment] 2015-02-24 20:00
Tomorrow I can test and confirm. Thanks for solving it so quickly!!

Robert

**Comment by robert83ft** [comment] 2015-02-25 07:14
Hi,

Works fine now. Just one short question ... I used to place my jobs in **global.php** like this :

```php
/* Cron type entries for scheduled tasks */
Event::listen('cron.collectJobs', function() {
    Cron::setLaravelLogging(false);

    // Read and verify temp every minute
    Cron::add('Read server room temperature', '* * * * *', function() {
        Log::debug('Running read temperature cron task.');
        App::make('ServersController')->readTemp();

        Log::debug('Running verifytemp cron task.');
        App::make('ServersController')->verifytemp();
        return null;
    });
```
...... + other


1. Can you tell me if I'm doing it correctly? The outcome seems as desired.
2. Where would I put that in Laravel5?

Robert

**Comment by liebig** [comment] 2015-02-25 10:00
Hi Robert,

Thank you for testing. Your code looks good, but I think you have to enter the full namespace in the `App:make` method. For example `App::make('App\Http\Controllers\ServersController')->readTemp();`.

Laravel 5 has no more a `global.php` file, so please use the `/path/to/laravel5/app/Providers/AppServiceProvider.php` at the `boot` method. If you are using this file, please note the different namespace and please add a `\` in front of your `Event`, `Cron`, `Log` and `App` objects or you get a class not found exception.

```php
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap any application services.
	 *
	 * @return void
	 */
	public function boot() {
		//
            
            \Event::listen('cron.collectJobs', function() {
                \Cron::setLaravelLogging(false);

                // Read and verify temp every minute
                \Cron::add('Read server room temperature', '* * * * *', function() {
                    \Log::debug('Running read temperature cron task.');
                    \App::make('App\Http\Controllers\ServersController')->readTemp();

                    \Log::debug('Running verifytemp cron task.');
                    \App::make('App\Http\Controllers\ServersController')->verifytemp();
                    return null;
                });
            });
	}
}
```

Please let me know if this works for you.
I will polish my code a little bit, edit the README and after that, close this ticket.

Thanks,
Marc

**Comment by robert83ft** [comment] 2015-02-25 10:22
Hi Marc,

Yes,  your points are all valid .. I copy/pasted the L4 code .. as I'm in the process of moving it to L5 ...
Thanks for pointing me to `/path/to/laravel5/app/Providers/AppServiceProvider.php` .. I'm still learning Laravel .. and that part was not clear.

Regards,
Robert

**Comment by liebig** [comment] 2015-03-02 13:03
Work is done with commit cd0ba32f680571424b9e5fbaf8956e7776e59b37
Thank you for your support.

**Closed by liebig** 2015-03-02 13:03 UTC
Labels: enhancement
